POST http://localhost:3003/api/blogs
Content-Type: application/json

{   
    "author": "Martti",
    "url": "non",
    "likes": 11,
    "title": "Blogs have their user",
    "userId": "66b9445a85ab68e4121dca09"
}